# -*- coding: utf-8 -*-
"""Vision_Transformer_v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M7x89WWVBcPAVqu_6KDGUM6kFRocHykt
"""

# -----------------------------
# Imports
# -----------------------------
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torchvision import datasets, transforms
from torch.utils.data import DataLoader
import random
import numpy as np
import os

# -----------------------------
# Device configuration
# -----------------------------
device = "cuda" if torch.cuda.is_available() else "cpu"
print("Using device:", device)

# -----------------------------
# Reproducibility
# -----------------------------
torch.manual_seed(42)
torch.cuda.manual_seed(42)
random.seed(42)
np.random.seed(42)

# -----------------------------
# Hyperparameters
# -----------------------------
BATCH_SIZE    = 128
EPOCHS        = 10
LEARNING_RATE = 3e-4

IMAGE_SIZE   = 32
PATCH_SIZE   = 4
CHANNELS     = 3
NUM_CLASSES  = 10

EMBED_DIM    = 256   # Must be divisible by NUM_HEADS
NUM_HEADS    = 8
DEPTH        = 6
MLP_DIM      = 512
DROP_RATE    = 0.1

# ============================================================
# Dataset & DataLoader
# ============================================================

transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize(
        (0.5, 0.5, 0.5),
        (0.5, 0.5, 0.5)
    )
])

train_dataset = datasets.CIFAR10(
    root="data",
    train=True,
    download=True,
    transform=transform
)

test_dataset = datasets.CIFAR10(
    root="data",
    train=False,
    download=True,
    transform=transform
)

train_loader = DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True
)

test_loader = DataLoader(
    test_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False
)

# ============================================================
# Patch Embedding
# Image → Patch Tokens
# Hardware mapping: Conv2D = GEMM
# ============================================================

class PatchEmbedding(nn.Module):
    def __init__(self, img_size, patch_size, in_channels, embed_dim):
        super().__init__()

        self.proj = nn.Conv2d(
            in_channels=in_channels,
            out_channels=embed_dim,
            kernel_size=patch_size,
            stride=patch_size
        )

        num_patches = (img_size // patch_size) ** 2
        self.cls_token = nn.Parameter(torch.randn(1, 1, embed_dim))
        self.pos_embed = nn.Parameter(torch.randn(1, num_patches + 1, embed_dim))

    def forward(self, x):
        B = x.size(0)

        # (B, C, H, W) → (B, E, H', W')
        x = self.proj(x)

        # (B, E, H', W') → (B, N, E)
        x = x.flatten(2).transpose(1, 2)

        cls = self.cls_token.expand(B, -1, -1)
        x = torch.cat((cls, x), dim=1)

        x = x + self.pos_embed
        return x

# ============================================================
# Manual Multi-Head Self Attention
# Explicit Q, K, V (RTL-friendly)
# ============================================================

class MultiHeadSelfAttention(nn.Module):
    def __init__(self, embed_dim, num_heads):
        super().__init__()
        assert embed_dim % num_heads == 0

        self.num_heads = num_heads
        self.head_dim = embed_dim // num_heads
        self.scale = self.head_dim ** -0.5

        self.qkv  = nn.Linear(embed_dim, embed_dim * 3, bias=False)
        self.proj = nn.Linear(embed_dim, embed_dim, bias=False)

    def forward(self, x):
        B, N, C = x.shape

        qkv = self.qkv(x)
        qkv = qkv.reshape(B, N, 3, self.num_heads, self.head_dim)
        qkv = qkv.permute(2, 0, 3, 1, 4)

        q, k, v = qkv[0], qkv[1], qkv[2]

        attn = (q @ k.transpose(-2, -1)) * self.scale
        attn = attn.softmax(dim=-1)

        out = attn @ v
        out = out.transpose(1, 2).reshape(B, N, C)

        return self.proj(out)

# ============================================================
# Feed Forward Network (MLP)
# ============================================================

class MLP(nn.Module):
    def __init__(self, embed_dim, mlp_dim, drop_rate):
        super().__init__()
        self.fc1 = nn.Linear(embed_dim, mlp_dim)
        self.fc2 = nn.Linear(mlp_dim, embed_dim)
        self.dropout = nn.Dropout(drop_rate)

    def forward(self, x):
        x = self.dropout(F.gelu(self.fc1(x)))
        x = self.dropout(self.fc2(x))
        return x

# ============================================================
# Transformer Encoder Block (Pre-Norm)
# ============================================================

class TransformerEncoderLayer(nn.Module):
    def __init__(self, embed_dim, num_heads, mlp_dim, drop_rate):
        super().__init__()
        self.norm1 = nn.LayerNorm(embed_dim)
        self.attn  = MultiHeadSelfAttention(embed_dim, num_heads)
        self.norm2 = nn.LayerNorm(embed_dim)
        self.mlp   = MLP(embed_dim, mlp_dim, drop_rate)

    def forward(self, x):
        x = x + self.attn(self.norm1(x))
        x = x + self.mlp(self.norm2(x))
        return x

# ============================================================
# Vision Transformer
# ============================================================

class VisionTransformer(nn.Module):
    def __init__(self):
        super().__init__()

        self.patch_embed = PatchEmbedding(
            IMAGE_SIZE, PATCH_SIZE, CHANNELS, EMBED_DIM
        )

        self.encoder = nn.Sequential(
            *[
                TransformerEncoderLayer(
                    EMBED_DIM, NUM_HEADS, MLP_DIM, DROP_RATE
                )
                for _ in range(DEPTH)
            ]
        )

        self.norm = nn.LayerNorm(EMBED_DIM)
        self.head = nn.Linear(EMBED_DIM, NUM_CLASSES)

    def forward(self, x):
        x = self.patch_embed(x)
        x = self.encoder(x)
        x = self.norm(x)
        cls_token = x[:, 0]
        return self.head(cls_token)

# ============================================================
# Training & Evaluation
# ============================================================

model = VisionTransformer().to(device)
criterion = nn.CrossEntropyLoss()
optimizer = optim.AdamW(model.parameters(), lr=LEARNING_RATE)

def train(model, loader):
    model.train()
    total_loss, correct = 0, 0

    for x, y in loader:
        x, y = x.to(device), y.to(device)

        optimizer.zero_grad()
        out = model(x)
        loss = criterion(out, y)
        loss.backward()
        optimizer.step()

        total_loss += loss.item() * x.size(0)
        correct += (out.argmax(1) == y).sum().item()

    return total_loss / len(loader.dataset), correct / len(loader.dataset)

def evaluate(model, loader):
    model.eval()
    correct = 0
    with torch.inference_mode():
        for x, y in loader:
            x, y = x.to(device), y.to(device)
            out = model(x)
            correct += (out.argmax(1) == y).sum().item()
    return correct / len(loader.dataset)

# ============================================================
# TRAINING LOOP
# ============================================================

for epoch in range(EPOCHS):
    train_loss, train_acc = train(model, train_loader)
    test_acc = evaluate(model, test_loader)

    print(
        f"Epoch [{epoch+1}/{EPOCHS}] | "
        f"Loss: {train_loss:.4f} | "
        f"Train Acc: {train_acc*100:.2f}% | "
        f"Test Acc: {test_acc*100:.2f}%"
    )

# ============================================================
# EXPORT WEIGHTS FOR RTL (IMPORTANT PART)
# ============================================================

def export_weights_to_files(model, save_dir="/content/vit_weights"):
    """
    Saves every model parameter as a .npy file.
    These files are later converted to fixed-point
    and loaded into Verilog ROMs.
    """
    os.makedirs(save_dir, exist_ok=True)
    model.eval()

    for name, param in model.named_parameters():
        filename = name.replace(".", "_") + ".npy"
        path = os.path.join(save_dir, filename)
        np.save(path, param.detach().cpu().numpy())

    print(f"✅ All weights exported to: {save_dir}")

export_weights_to_files(model)

# ============================================================
# END OF FILE
# ============================================================

